"use client";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";
import Navbar from "@/components/ui/navbar";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const paramsNav = usePathname();
  const hideNavbar = ['/auth/sign-in', '/auth/sign-up'].includes(paramsNav);
  const queryClient = new QueryClient();

  return (
    <html lang="en">
      <title>HomeTest</title>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QueryClientProvider client={queryClient}>
          {!hideNavbar && <Navbar/>}
            {children}
            <Toaster/>
        </QueryClientProvider>
      </body>
    </html>
  );
}
